import React from "react";
import Head from "next/head";
import NavBar from "./navbar";


function Layout({children,title}) {
    return(
        <div>
            <Head>
                <title>Tienda {title?`| ${title}`:''}</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
            </Head>
            <h1>cabeza</h1>
           <main>
               <NavBar children={children}/>
            <div>{children}</div>
           </main>
            <footer>
            <h1>pie</h1>
            </footer>
        </div>

    )

}
export default Layout;